# site settings

title: Shashwat Adhikari
description: Personal Website
taglong: A personal site to spill out my wacky thoughts!
tagshort: Jekyll theme
url: https://shashwatadh.github.io/
baseurl: ""
permalink: pretty
repo: https://github.com/ShashwatAdh/ShashwatAdh.github.io

# author settings

author:
  name: Shashwat Adhikari
  email: shashwatmail4@gmail.com
photo: /assets/Avatar_1.png

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
